# Generated by Django 3.1.7 on 2021-02-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InicioAITrainerWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clases_curso',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='clases_curso',
            old_name='Titulo',
            new_name='titulo',
        ),
    ]
